# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ssa.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import seplib
from PyQt5 import QtCore, QtGui, QtWidgets

class handlers():
    filename = ''
    def setupHandlers(obj):
        obj.Separar.clicked.connect(lambda:handlers.Separar(obj))
        obj.Select.clicked.connect(lambda: handlers.Selecionar(obj))
        obj.Juntar.clicked.connect(lambda: handlers.Juntar(obj))

    def Separar(obj):
        try: 
            partes  = int(obj.Partes.text())
            seplib.separar(obj.label_4.text(),partes)
        except:
            try:
                #print(int(os.path.getsize(obj.label_4.text())))
                #print((int(obj.TamanhoMaximo.text())*1000*1000*int(1000/1024)))
                partes = int(os.path.getsize(obj.label_4.text())/(int(obj.TamanhoMaximo.text())*1000*1000))+1
                print(partes)
                seplib.separar(obj.label_4.text(),partes)
            except:
                print('Deuruim')

    def Juntar(obj):
        seplib.juntar(obj.label_4.text())

    def Selecionar(obj):
        dialog = QtWidgets.QFileDialog(None,"","","")
        dialog.setFileMode(QtWidgets.QFileDialog.AnyFile)
        if dialog.exec_():
            file_name = dialog.selectedFiles()[0]
            obj.label_4.setText(file_name)
            filename = file_name

        

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.Partes = QtWidgets.QLineEdit(Dialog)
        self.Partes.setGeometry(QtCore.QRect(10, 250, 81, 20))
        self.Partes.setObjectName("Partes")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.label.setObjectName("label")
        self.TamanhoMaximo = QtWidgets.QLineEdit(Dialog)
        self.TamanhoMaximo.setGeometry(QtCore.QRect(140, 250, 71, 20))
        self.TamanhoMaximo.setObjectName("TamanhoMaximo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 230, 121, 16))
        self.label_2.setObjectName("label_2")
        self.Separar = QtWidgets.QPushButton(Dialog)
        self.Separar.setGeometry(QtCore.QRect(300, 220, 75, 23))
        self.Separar.setObjectName("Separar")
        self.Juntar = QtWidgets.QPushButton(Dialog)
        self.Juntar.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.Juntar.setObjectName("Juntar")
        self.Select = QtWidgets.QPushButton(Dialog)
        self.Select.setGeometry(QtCore.QRect(120, 120, 161, 23))
        self.Select.setObjectName("Select")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 341, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ssaw10e.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 381, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.Partes.raise_()
        self.label.raise_()
        self.TamanhoMaximo.raise_()
        self.label_2.raise_()
        self.Separar.raise_()
        self.Juntar.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.Select.raise_()

        handlers.setupHandlers(self)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Numero de partes:"))
        self.label_2.setText(_translate("Dialog", "Tamanho Maximo (MB):"))
        self.Separar.setText(_translate("Dialog", "SEPARAR"))
        self.Juntar.setText(_translate("Dialog", "JUNTAR"))
        self.Select.setText(_translate("Dialog", "Selecionar Arquivo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
